create extension if not exists pgcrypto;

create table public.users (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) > 0),
  created_at timestamptz not null default now()
);

create table public.photo_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  photo_url text not null,
  clue_text text not null,
  clue_emoji text not null,
  created_at timestamptz not null default now()
);

create index photo_submissions_user_id_idx
  on public.photo_submissions (user_id);

create index photo_submissions_created_at_idx
  on public.photo_submissions (created_at desc);

create table public.bingo_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  photo_submission_1 bigint not null references public.photo_submissions(id),
  photo_submission_2 bigint not null references public.photo_submissions(id),
  photo_submission_3 bigint not null references public.photo_submissions(id),
  photo_submission_4 bigint not null references public.photo_submissions(id),
  photo_submission_5 bigint not null references public.photo_submissions(id),
  created_at timestamptz not null default now()
);

create index bingo_submissions_user_id_idx
  on public.bingo_submissions (user_id);

create table public.game_state (
  id integer primary key,
  state text not null,
  constraint game_state_known_rows check (
    (id = 0 and state in ('pending', 'active', 'finished'))
    or (id = 1 and state in ('test', 'active'))
  )
);

insert into public.game_state (id, state)
values
  (0, 'pending'),
  (1, 'active');

alter table public.users enable row level security;
alter table public.photo_submissions enable row level security;
alter table public.bingo_submissions enable row level security;
alter table public.game_state enable row level security;

create policy "Public access to users"
  on public.users
  for all
  to anon, authenticated
  using (true)
  with check (true);

create policy "Public access to photo submissions"
  on public.photo_submissions
  for all
  to anon, authenticated
  using (true)
  with check (true);

create policy "Public access to bingo submissions"
  on public.bingo_submissions
  for all
  to anon, authenticated
  using (true)
  with check (true);

create policy "Public read access to game state"
  on public.game_state
  for select
  to anon, authenticated
  using (true);

create policy "Public update access to game state"
  on public.game_state
  for update
  to anon, authenticated
  using (true)
  with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.users to anon, authenticated;
grant select, insert, update, delete on public.photo_submissions to anon, authenticated;
grant select, insert, update, delete on public.bingo_submissions to anon, authenticated;
grant select, update on public.game_state to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('silva-lee-bingo', 'silva-lee-bingo', true);

create policy "Public read access to bingo photos"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'silva-lee-bingo');

create policy "Public upload access to bingo photos"
  on storage.objects
  for insert
  to anon, authenticated
  with check (bucket_id = 'silva-lee-bingo');

create policy "Public delete access to bingo photos"
  on storage.objects
  for delete
  to anon, authenticated
  using (bucket_id = 'silva-lee-bingo');

alter publication supabase_realtime
  add table public.users, public.photo_submissions, public.game_state;
